FROM emscripten/emsdk

# RUN apt install -y python3-venv pkg-config libgl-dev libopengl-dev libglfw3-dev libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev

RUN pip3 install 'conan==2.*'

