name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        build_type: [ Debug, Release ]
        build_profile: [ linux, emscripten ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: do build
      run: >
        BUILD_TYPE=${{matrix.build_type}}
        ${{github.workspace}}/ci/container.sh
        /tmp/cc.fyi.pong/ci/build.sh

    - name: upload
      if: matrix.build_type == 'Release' && matrix.build_profile == 'emscripten'
      uses: actions/upload-artifact@v4
      with:
        name: github-pages
        path: cmake-build-*/pong-*.tar.gz

    - name: deploy
      uses: actions/deploy-pages@v4
