name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        build_profile: [ linux, emscripten ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: do build
      run: >
        BUILD_TYPE=${{matrix.build_type}}
        BUILD_PROFILE=${{matrix.build_profile}}
        ${{github.workspace}}/ci/${{matrix.build_profile}}/container.sh
        ${{github.workspace}}/ci/build.sh
