name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        build_profile: [ linux, emscripten ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: do build
      run: >
        BUILD_TYPE=${{matrix.build_type}}
        ${{github.workspace}}/ci/container.sh
        /tmp/cc.fyi.pong/ci/build.sh
